export const cxcs = [
  {
    id: "cxc-001",
    name: "Homer Simpson",
    fullName: "Homer Jay Simpson",
    pagePath: "homer.html",
    selectionImage: "images/homer.png",
    detailImage: "images/homer_e.png",
    description:
      "Homer Jay Simpson is the father of the Simpson family and works at the Springfield Nuclear Power Plant. He is lovable, stubborn, and always chasing the next donut or easy solution.",
    voiceActor: "Dan Castellaneta",
    actorImage: "images/DanC.png",
    imdb: "https://www.imdb.com/name/nm0144657/",
    audio: ["audio/fallen_behind.wav", "audio/get_it.wav"],
    memes: [
      "memes/homer/image1.png",
      "memes/homer/image2.png",
      "memes/homer/image3.png",
      "memes/homer/image4.png",
      "memes/homer/image5.png",
    ],
  },
  {
    id: "cxc-002",
    name: "Marge Simpson",
    fullName: 'Marjorie "Marge" Simpson',
    pagePath: "marge.html",
    selectionImage: "images/marge.png",
    detailImage: "images/marge_e.png",
    description:
      "Marge Simpson is the caring and patient mother of the Simpson family. She keeps the household together and always tries to do what is right.",
    voiceActor: "Julie Kavner",
    actorImage: "images/JulleK.png",
    imdb: "https://www.imdb.com/name/nm0001413/?ref_=fn_t_1",
    audio: ["audio/Marge1.wav", "audio/Marge2.wav"],
    memes: [
      "memes/marge/image1.png",
      "memes/marge/image2.png",
      "memes/marge/image3.png",
      "memes/marge/image4.png",
      "memes/marge/image5.png",
    ],
  },
  {
    id: "cxc-003",
    name: "Bart Simpson",
    fullName: 'Bartholemew Jojo "Bart" Simpson',
    pagePath: "bart.html",
    selectionImage: "images/bart.png",
    detailImage: "images/bart_e.png",
    description:
      "Bart Simpson is the mischievous oldest child of the Simpson family. He loves pranks, skateboarding, and pushing his parents' limits.",
    voiceActor: "Nancy Cartwright",
    actorImage: "images/NancyC.png",
    imdb: "https://www.imdb.com/name/nm0004813/?ref_=fn_t_1",
    audio: ["audio/Bart1.wav", "audio/bart2.wav"],
    memes: [
      "memes/bart/image1.png",
      "memes/bart/image2.png",
      "memes/bart/image3.png",
      "memes/bart/image4.png",
      "memes/bart/image5.png",
    ],
  },
  {
    id: "cxc-004",
    name: "Lisa Simpson",
    fullName: "Lisa Marie Simpson",
    pagePath: "lisa.html",
    selectionImage: "images/lisa.png",
    detailImage: "images/lisa_e.png",
    description:
      "Lisa Simpson is the intelligent and idealistic middle child of the Simpson family. She loves learning, music, and fighting for justice.",
    voiceActor: "Yeardley Smith",
    actorImage: "images/YeardelyS.png",
    imdb: "https://www.imdb.com/name/nm0810379/?ref_=fn_t_1",
    audio: ["audio/Lisa1.wav", "audio/Lisa2.wav"],
    memes: [
      "memes/lisa/image1.png",
      "memes/lisa/image2.png",
      "memes/lisa/image3.png",
      "memes/lisa/image4.png",
      "memes/lisa/image5.png",
    ],
  },
  {
    id: "cxc-005",
    name: "Maggie Simpson",
    fullName: 'Margaret "Maggie" Simpson',
    pagePath: "maggie.html",
    selectionImage: "images/maggie.png",
    detailImage: "images/maggie_e.png",
    description:
      "Maggie Simpson is the baby of the family, often quiet but very expressive. She may be small, but she always has her pacifier and a surprising amount of personality.",
    voiceActor: "Lindsay Lohan",
    actorImage: "images/LindsayL.png",
    imdb: "https://www.imdb.com/name/nm0517820/?ref_=fn_t_1",
    audio: [],
    memes: [
      "memes/maggie/image1.png",
      "memes/maggie/image2.png",
      "memes/maggie/image3.png",
      "memes/maggie/image4.png",
      "memes/maggie/image5.png",
    ],
  },
  {
    id: "cxc-006",
    name: "Burns",
    fullName: 'Charles Montgomery "Monty" Burns',
    pagePath: "burns.html",
    selectionImage: "images/burns.png",
    detailImage: "images/burns_e.png",
    description:
      "Mr. Burns is the wealthy, ruthless owner of the Springfield Nuclear Power Plant. He is famous for his cold attitude and evil schemes.",
    voiceActor: "Harry Shearer",
    actorImage: "images/HarryS.png",
    imdb: "https://www.imdb.com/name/nm0733427/?ref_=fn_t_1",
    audio: ["audio/Burns1.wav", "audio/Burns2.wav"],
    memes: [
      "memes/burns/image1.png",
      "memes/burns/image2.png",
      "memes/burns/image3.png",
      "memes/burns/image4.png",
      "memes/burns/image5.png",
      "memes/burns/image6.png",
    ],
  },
  {
    id: "cxc-007",
    name: "Apu",
    fullName: "Apu Nahasapeemapetilon",
    pagePath: "apu.html",
    selectionImage: "images/apu.png",
    detailImage: "images/apu_e.png",
    description:
      "Apu is the hardworking owner of the Kwik-E-Mart convenience store. He is polite, clever, and always ready to help out customers in Springfield.",
    voiceActor: "Hank Azaria",
    actorImage: "images/HankA.png",
    imdb: "https://www.imdb.com/name/nm0000279/?ref_=fn_t_1",
    audio: ["audio/Apu1.wav", "audio/Apu2.wav"],
    memes: [
      "memes/apu/image1.png",
      "memes/apu/image2.png",
      "memes/apu/image3.png",
      "memes/apu/image4.png",
      "memes/apu/image5.png",
    ],
  },
  {
    id: "cxc-008",
    name: "Moe",
    fullName: 'Morris "Moe" Szyslak',
    pagePath: "moe.html",
    selectionImage: "images/moe.png",
    detailImage: "images/moe_e.png",
    description:
      "Moe Szyslak is the grumpy bartender and owner of Moe's Tavern. He runs the bar with a rough attitude but a surprisingly warm heart under the surface.",
    voiceActor: "Hank Azaria",
    actorImage: "images/HankA.png",
    imdb: "https://www.imdb.com/name/nm0000279/?ref_=fn_t_1",
    audio: ["audio/Moe1.wav", "audio/Moe2.wav"],
    memes: [
      "memes/moe/image1.png",
      "memes/moe/image2.png",
      "memes/moe/image3.png",
      "memes/moe/image4.png",
      "memes/moe/image5.png",
    ],
  },
];

export const homes = [
  {
    id: "home-001",
    name: "Simpson House",
    description: [
      "The Simpson family lives in their famous home at 742 Evergreen Terrace. The house has appeared in almost every episode of the series and is one of the most recognizable cartoon homes in television history.",
    ],
    gallery: [
      {
        src: "images/home1.png",
        alt: "Simpson Living Room",
        caption: "Living Room",
      },
      {
        src: "images/home2.png",
        alt: "Simpson Dining Room",
        caption: "Dining Room",
      },
      { src: "images/home3.png", alt: "Simpson Bedroom", caption: "Bedroom" },
      { src: "images/home4.png", alt: "Simpson Bathroom", caption: "Bathroom" },
      {
        src: "images/home5.png",
        alt: "Simpson House Top View",
        caption: "Top View",
      },
      {
        src: "images/home6.png",
        alt: "Simpson Floor Plan",
        caption: "Floor Plan",
      },
      { src: "images/home7.png", alt: "Simpson Yard", caption: "Yard" },
      {
        src: "images/home8.png",
        alt: "Simpson Night View",
        caption: "Night View",
      },
    ],
  },
  {
    id: "home-002",
    name: "Moe's Tavern",
    description: [
      "Moe's Tavern is Springfield's iconic dive bar where Homer and his friends gather for cheap beer, awkward conversations, and the kind of trouble only Moe Szyslak can attract.",
      "The gallery images show Moe behind the bar, a noisy night with patrons, the famous regulars, the front entrance with a waiting line, a neon beer sign, the pool table area, and the tavern exterior.",
    ],
    gallery: [
      {
        src: "images/moes1.png",
        alt: "Moe serving Homer a beer",
        caption: "Moe serving Homer at the bar",
      },
      {
        src: "images/moes2.png",
        alt: "A crowded night inside Moe's Tavern",
        caption: "Rowdy evening at Moe's",
      },
      {
        src: "images/moes3.png",
        alt: "A wild party inside Moe's Tavern",
        caption: "Chaos and characters at the bar",
      },
      {
        src: "images/moes5.png",
        alt: "Patrons waiting outside Moe's Tavern",
        caption: "Customers lined up outside",
      },
      {
        src: "images/moes6.png",
        alt: "Moe facing police over the pet store dispute",
        caption: "Police responding to Moe's pet store dispute",
      },
      {
        src: "images/moes7.png",
        alt: "Moe dealing with a tense bar argument near the pool table",
        caption: "Moe managing a tense confrontation at the pool table",
      },
      {
        src: "images/moes8.png",
        alt: "Moe's Tavern exterior at night",
        caption: "Moe's night exterior",
      },
      {
        src: "images/moes.png",
        alt: "Moe's Tavern building exterior",
        caption: "The bar's exterior facade",
      },
    ],
  },
  {
    id: "home-003",
    name: "Kwik-E-Mart",
    description: [
      "Kwik-E-Mart is Springfield's famous convenience store owned by Apu Nahasapeemapetilon. It is open 24 hours a day, sells Squishees, Buzz Cola, snacks, and oddball items, and is one of the show's most iconic community landmarks.",
    ],
    gallery: [
      {
        src: "images/k_mart1.png",
        alt: "Apu behind the Kwik-E-Mart counter",
        caption: "Apu working the register",
      },
      {
        src: "images/k_mart2.png",
        alt: "Customers waiting at the Kwik-E-Mart checkout",
        caption: "Busy checkout line",
      },
      {
        src: "images/k_mart3.png",
        alt: "Bart inside the Kwik-E-Mart",
        caption: "Bart shopping inside the store",
      },
      {
        src: "images/k_mart4.png",
        alt: "Homer and Lisa inside the Kwik-E-Mart",
        caption: "Homer and Lisa at the entrance",
      },
      {
        src: "images/k_mart5.png",
        alt: "Kwik-E-Mart arcade game",
        caption: "Retro arcade machine in the shop",
      },
      {
        src: "images/k_mart6.png",
        alt: "Apu being threatened in the store",
        caption: "A tense robbery moment",
      },
      {
        src: "images/kmart.png",
        alt: "Kwik-E-Mart exterior",
        caption: "Store exterior facade",
      },
    ],
  },
];
